### ISSUE TITLE
Omitted file.With error block causing crash

### ISSUE THREAD

**Issue by perimosocordiae** [asoffer/Icarus#100]
Here's a reproducer (named "repro.ic"):

```
file ::= import "file.ic"

file.With("repro.ic") open [f: file.File] {
}
```

----
Output:

```
[139883213363016 frontend/source/buffer.cc:41] Assertion failed
    Expected: iter != line_start_.end()
         LHS: (Unprintable value of type N9__gnu_cxx17__normal_iteratorIPKN8frontend9SourceLocESt6vectorIS2_SaIS2_EEEE)[00 00 00 00 00 00 00 00]
         RHS: (Unprintable value of type N9__gnu_cxx17__normal_iteratorIPKN8frontend9SourceLocESt6vectorIS2_SaIS2_EEEE)[00 00 00 00 00 00 00 00]
*** SIGABRT received at time=1640785845 on cpu 1 ***
PC: @     0x7f3919480808  (unknown)  pthread_kill
    @          0x18f65c0         64  absl::WriteFailureInfo()
    @          0x18f62a4        224  absl::AbslFailureSignalHandler()
    @     0x7f391942c520  (unknown)  (unknown)
Aborted (core dumped)
```

Note that the following file runs without issue:

```
file ::= import "file.ic"
errno ::= import "errno.ic"

file.With("repro.ic") open [f: file.File] {
} error [e: errno.error] {
}
```

**Comment by asoffer** [comment]
There are a few features we need to fix this:

1. Scopes need a way to specify which blocks are required. In #81 Will suggested marking that on the scope_context type, which seems like the natural place to put it.
2. Even with this, `error` is an optional block, so we need a way to query whether the block is present.
3. We need a mechanism to act on the result of that query at compile-time. This can be something like C++ if-constexpr or D's static-if.

Altogether, we might end up modifying the `With` scope definition to include something like
```
#{const} if (ctx.?error) {
  e >> ctx.error
}
```
