### ISSUE TITLE
file.Lines returns slices of length 0xAAAAAAAAAAAAAAAA

### ISSUE THREAD

**Issue by perimosocordiae** [asoffer/Icarus#110]
Looks like the length field of the slice is left uninitialized?

```
$ icarus repro.ic
length: 12297829382473034410: file ::= import "file.ic"
length: 12297829382473034410: io ::= import "io.ic"
length: 12297829382473034410: 
length: 12297829382473034410: file.With("repro.ic") open [f: file.File] {
length: 12297829382473034410:   file.Lines(f) each [line: []char] {
length: 12297829382473034410:     io.Print("length: ", line.length, ": ", line)
length: 12297829382473034410:   }
length: 12297829382473034410: }
length: 12297829382473034410:
```

**Comment by asoffer** [comment]
Yes, we write 0xAA bytes in debug mode into memory that would be uninitialized in opt-mode, so this is a bug in the IR-generation. We're likely reading the register holding the length but never wrote to it.

To clarify, it's reading the file correctly just the length is wrong? Meaning the call to `printf("%*s", ...)` likely is getting lucky regarding null terminators.

**Comment by perimosocordiae** [comment]
Yup, the printing must be hitting the null byte and stopping, rather than trying to print all 0xAAAA... bytes.

**Comment by perimosocordiae** [comment]
This bug is relatively new, by the way, because the length was initialized properly back when I wrote my day 9 advent solution. I suspect it popped up in the last week or two's changes.
