### ISSUE TITLE
Fat arrow functions are broken

### ISSUE THREAD

**Issue by perimosocordiae** [asoffer/Icarus#2]
Reproducer:

```
foo ::= (x: float64) => { x * 2 }

foo(5.3)
```

Output:

```
[compiler/verify_type.cc 139772932585216: 1606 Visit] Not yet implemented.
(log an error, [](float64),  vs , [const](type))
*** SIGABRT received at time=1583094863 ***
```

**Comment by asoffer** [comment]
Interesting... this shouldn't make it past the parser. The short answer is, fat-arrow functions don't need braces, so this should be written an `(x: float64) => x * 2`.

I roughly see why the parser is accepting it, (and thinking it's a designated initializer). Designated initializers look like `MyType.{ a = x, b = y }`. And should be parsed as `<expr> <dot> <braced_stmts>` but we're loose on the "dot" and accept any binary operator (in this case, "=>").
