### ISSUE TITLE
Assignments to out of scope variables could have better error messages.

### ISSUE THREAD

**Issue by asoffer** [asoffer/Icarus#30]
This should produce an error but does not.
```
i := 0
f ::= () -> () { i = 1 }
```

**Comment by asoffer** [comment]
Changing this to an enhancement now that there is an error message (just not a great one).

**Comment by perimosocordiae** [comment]
What's the syntax for capturing a local variable?

**Comment by asoffer** [comment]
No such syntax exists. I'd like a syntax for capturing but I think we first need a solution for lifetime tracking. Or at least start captures with by-value only. If you're interested, feel free to open an issue as a proposal for syntax and semantics.
