### ISSUE TITLE
Emit error message for invalid block names.

### ISSUE THREAD

**Issue by asoffer** [asoffer/Icarus#40]
// The capital `T` causes a crash.
if (condition) Then { ... }

**Comment by perimosocordiae** [comment]
Along these lines, a better error message for a missing block name would be great as well:

```
if (cond) { ... }
```

**Comment by asoffer** [comment]
It's true, although it might be nice to have a block bindable to `--` or `first` or something to indicate that it must always be present and must always be the first block and would be implicit, so that `if (cond) { ... }` would be valid.
