### ISSUE TITLE
Identifiers must have an alpha-character in them.

### ISSUE THREAD

**Issue by asoffer** [asoffer/Icarus#44]
We use `_` as a digit separator in numbers, and allow them to be placed anywhere, so `0_` would be considered a valid number, but `_0` would be an identifier. This seems to be needlessly subtle.

We should change the rules so that an identifier must
* Have only alphanumeric and underscore characters
* Not start with a numeric character
* Have at least one alpha character.

These rules seem relatively straightforward and have the added benefit of making `_` not a valid identifier (reserving it for future use like indicating ignored values or pattern matching).

**Comment by perimosocordiae** [comment]
Why not ban trailing underscores in numeric literals? Effectively this means underscores may only appear internally in numbers, as implied by the name "separator".

Then state: numbers must start with a digit, and identifiers must not start with a digit. Seems pretty clear to me.

**Comment by asoffer** [comment]
This still means that `12_3` and `1_23` are numbers but `_123` is an identifier. I might be okay banning this, but I think it's best to demand that a sequence of characters containing only digits and underscores is not an identifier. It might be a number, and I'm okay banning some outright, but it shouldn't be an identifier.

**Comment by perimosocordiae** [comment]
Python supports `_1` as an identifier, but I'm fine banning it.

**Comment by asoffer** [comment]
Interesting. That's pretty compelling. I didn't realize Python allowed underscore as a digit separator.
