### ISSUE TITLE
User defined error messages

### ISSUE THREAD

**Issue by asoffer** [asoffer/Icarus#66]
`error` should be a built-in function that accepts two arguments. The first should be a type, and the second  a `[]char`. When doing type verification, this expression will emit the second argument as a diagnostic, but will be determined to have it's first argument as a type.

For example,

```
sizeof ::= (T: type) -> u64 {
  if (T == bool) {
    return 1
  } else {
    return error(u64, "Only bool is currently supported")
  }
}
```

We might also want a non-expression version. Maybe this is just a one-argument version (only the `[]char` message).

**Comment by perimosocordiae** [comment]
Would this be similar to the `panic!()` macro from Rust?

**Comment by asoffer** [comment]
No, this is for generating compile-time diagnostics. Functions calling this cannot be called at runtime. This would allow library authors to emit better diagnostics for compilation errors using their libraries.

**Comment by perimosocordiae** [comment]
Ah, so more akin to `static_assert` from C++?
