### ISSUE TITLE
Emit destructors correctly for block nodes

### ISSUE THREAD

**Issue by asoffer** [asoffer/Icarus#69]
Ethos is especially difficult when dealing with labelled yields (e.g., `#.my_label << 17`) which may jump over an arbitrary number of block exits and need to destroy everything in-between.

**Comment by perimosocordiae** [comment]
Is this the same issue as gh-61?

**Comment by asoffer** [comment]
That one is only about scope state. This is about objects declared in a block.

**Comment by asoffer** [comment]
With the changes made for #81 this should be fixed now.
