### ISSUE TITLE
ir::Integer type doesn't support *=

### ISSUE THREAD

**Issue by perimosocordiae** [asoffer/Icarus#92]
This one fails in a funky way:

```
x := 1
x *= 2
```

Error message:

```
[140472633321288 :0] Assertion failed
    Expected: found == true
         LHS: false
         RHS: true
```

Note that this does work for `x += 2`, somehow.

**Comment by perimosocordiae** [comment]
Also if you change the first line to `x: i64 = 1` then everything works as expected.

**Comment by asoffer** [comment]
It's rather annoying, but the "correct" fix here according to the intended language semantics at the moment would be to emit an error on `x := 1`, because you can't use `integer` at run-time.

**Comment by perimosocordiae** [comment]
Related crash with the same error message: casting an `integer` to f64:

```
x := 1
x as f64
```
