### ISSUE TITLE
Improve the user-accessible abort mechanism

### ISSUE THREAD

**Issue by perimosocordiae** [asoffer/Icarus#97]
This would be the runtime version of gh-66, similar to Rust's `panic!()` or the C++ `std::abort()`.

**Comment by perimosocordiae** [comment]
Oh wait I forgot about the `abort()` built-in:
https://github.com/asoffer/Icarus/blob/2e94748d1b5bd556244c95727b77d78971ccdfb0/stdlib/core.ic#L95

But I'll leave this open until we have something that accepts a string for the error message (maybe implemented in the Icarus stdlib)

**Comment by asoffer** [comment]
Print and then abort? This feels like LOG(FATAL) which is valuable but needs a lot of design work.
